name: "build backend"

on:
  push:
    paths:
      - build-backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3

      - name: Setup OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica

      - name: cache maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
          restore-keys: ${{ runner.os }}-maven

      - name: build
        working-directory: ./nortis-backend
        run: mvn clean compile source:jar package

      - name: Test Reports
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "**/target/surefire-reports/TEST-*.xml"

      - name: prepare package
        run: mkdir staging && cp target/*.jar staging
        if: always()

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
